# Generated by Django 3.1.6 on 2021-02-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioput', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leraning_time',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
