# Generated by Django 3.1.6 on 2021-03-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioput', '0003_leraning_time_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='leraning_time',
            name='details',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
