# Generated by Django 3.1.7 on 2021-03-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ioput', '0004_leraning_time_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leraning_time',
            name='dt',
        ),
    ]
