# Generated by Django 3.1.7 on 2021-03-19 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioput', '0007_leraning_time_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leraning_time',
            name='dt',
        ),
        migrations.AddField(
            model_name='leraning_time',
            name='day',
            field=models.DateField(default=datetime.date(2021, 3, 19)),
        ),
        migrations.AddField(
            model_name='leraning_time',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leraning_time',
            name='details',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
