# Generated by Django 3.1.7 on 2021-04-17 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ioput', '0008_auto_20210319_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leraning_time',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
